language: java
# Attention, lu ceci chez Travis : Container-based infrastructure has been fully deprecated. Please remove
# any "sudo: false" keys in your .travis.yml file to use the fully-virtualized Linux infrastructure.
#sudo: false
install: true

addons:
  sonarcloud:
    organization: "ivandalbosco-github"
    token:
      secure: "7248ac8d3711f080dd66fa2426e71590aacebdcc"

jdk:
  - oraclejdk8

script:
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar
  - mvn clean package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
